### ISSUE TITLE
AMQPConnectionError on python test_simulation.py

### ISSUE THREAD

**Issue by sbenthall** [sbenthall/SHARKFin#66]
Running the test_simulation.py script gets me this error:

```
$ python test_simulation.py 
Pika version 1.2.0 connecting to ('127.0.0.1', 5672)
Socket failed to connect: <socket.socket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 49876)>; error=111 (Connection refused)
TCP Connection attempt failed: ConnectionRefusedError(111, 'Connection refused'); dest=(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('127.0.0.1', 5672))
AMQPConnector - reporting failure: AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused')
AMQP connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None.
AMQPConnectionWorkflow - reporting failure: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None
Connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None
Error in _create_connection().
Traceback (most recent call last):
  File "/home/sb/.local/lib/python3.8/site-packages/pika/adapters/blocking_connection.py", line 451, in _create_connection
    raise self._reap_last_connection_workflow_error(error)
pika.exceptions.AMQPConnectionError
Traceback (most recent call last):
  File "test_simulation.py", line 100, in <module>
    market = hpa.ClientRPCMarket(
  File "/home/sb/projects/econ-ark/markets/SHARKFin/simulate/../sharkfin/hark_portfolio_agents.py", line 605, in __init__
    self.init_rpc()
  File "/home/sb/projects/econ-ark/markets/SHARKFin/simulate/../sharkfin/hark_portfolio_agents.py", line 608, in init_rpc
    self.connection = pika.BlockingConnection(
  File "/home/sb/.local/lib/python3.8/site-packages/pika/adapters/blocking_connection.py", line 360, in __init__
    self._impl = self._create_connection(parameters, _impl_class)
  File "/home/sb/.local/lib/python3.8/site-packages/pika/adapters/blocking_connection.py", line 451, in _create_connection
    raise self._reap_last_connection_workflow_error(error)
pika.exceptions.AMQPConnectionError
```

I assume this has something to do with RabbitMQ not being available. But there is zero documentation about how to set this up.

Also, it's probably better to use a simple, pure Python market by default, and have the RabbitMQ/AMMPS market as a configurable option, so it's easier to do local SHARKFin development.

**Comment by sbenthall** [comment]
Please : do rename `test_simulation` to `run_simulation` etc.

Please also: document these scripts so it's clear what order they need to be ran in. ..
